server:
  port: 8199
  servlet:
    context-path: /fdme
spring:
  datasource:
    password: 131Dundi@
    url: jdbc:mysql://192.168.0.106:3306/fdme?useUnicode=true&characterEncoding=utf-8
    username: root
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
logging:
  level:
    com.fdme.mapper: debug