server:
  port: 8199
  servlet:
    context-path: /fdme
spring:
  datasource:
    password: 151Dundi@@#
    url: jdbc:mysql://112.74.184.193:3306/fdme?useUnicode=true&characterEncoding=utf-8
    username: root
mybatis:
  mapper-locations: classpath:mapping/*.xml